name: "Check Title"
on:
  pull_request:
    types:
      # Check title when opened.
      - opened
      # Check title when new commits are pushed.
      # Required to use as a status check.
      - synchronize

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dylanvann/check-pull-request-title@v1
        with:
          # Match pull request titles in the form UI-1234 - Message.
          pattern: '^UI-\d* - '
